"""add allowed_scopes to agent and goal_drift_result to spend_audit_log

Revision ID: 631d066702f9
Revises: 20260501_0004
Create Date: 2026-05-08 17:44:08.760758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631d066702f9'
down_revision: Union[str, Sequence[str], None] = '20260501_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('allowed_scopes', sa.JSON(), nullable=True))
    op.add_column('spendauditlog', sa.Column('goal_drift_result', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spendauditlog', 'goal_drift_result')
    op.drop_column('agent', 'allowed_scopes')
    # ### end Alembic commands ###

