"""remove obsolete hitl fields from agent

Revision ID: 923589d9f23e
Revises: 631d066702f9
Create Date: 2026-05-17 02:52:55.508422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '923589d9f23e'
down_revision: Union[str, Sequence[str], None] = '631d066702f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent', 'hmac_secret_rotated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('agent', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('agent', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('agent_activity_agent_id_fkey'), 'agent_activity', type_='foreignkey')
    op.drop_constraint(op.f('agent_agent_id_key'), 'agent', type_='unique')
    op.drop_index(op.f('ix_agent_agent_id'), table_name='agent')
    op.create_index(op.f('ix_agent_agent_id'), 'agent', ['agent_id'], unique=True)
    op.drop_column('agent', 'hitl_phone_number')
    op.drop_column('agent', 'hitl_sms_fallback_high_risk')
    op.drop_column('agent', 'hitl_phone_verified_at')
    op.drop_column('agent', 'hitl_primary_channel')
    op.alter_column('agent_activity', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_foreign_key(None, 'agent_activity', 'agent', ['agent_id'], ['agent_id'])
    op.alter_column('dashboardnotification', 'acknowledged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('dashboardnotification', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('dashboardnotification', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('pendingspend', 'hitl_channel',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pendingspend', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('pendingspend', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('pendingspend', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('pendingspend_request_id_key'), 'pendingspend', type_='unique')
    op.drop_index(op.f('ix_pendingspend_request_id'), table_name='pendingspend')
    op.create_index(op.f('ix_pendingspend_request_id'), 'pendingspend', ['request_id'], unique=True)
    op.alter_column('spendauditlog', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_spendauditlog_onchain_tx_hash'), table_name='spendauditlog')
    op.drop_column('spendauditlog', 'onchain_tx_hash')
    op.drop_column('spendauditlog', 'payment_provider')
    op.drop_column('spendauditlog', 'payment_txn_id')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('users_auth_subject_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_auth_subject'), table_name='users')
    op.create_index(op.f('ix_users_auth_subject'), 'users', ['auth_subject'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_auth_subject_key'), 'users', ['auth_subject'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('spendauditlog', sa.Column('payment_txn_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('spendauditlog', sa.Column('payment_provider', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('spendauditlog', sa.Column('onchain_tx_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_spendauditlog_onchain_tx_hash'), 'spendauditlog', ['onchain_tx_hash'], unique=False)
    op.alter_column('spendauditlog', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_pendingspend_request_id'), table_name='pendingspend')
    op.create_index(op.f('ix_pendingspend_request_id'), 'pendingspend', ['request_id'], unique=False)
    op.create_unique_constraint(op.f('pendingspend_request_id_key'), 'pendingspend', ['request_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('pendingspend', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('pendingspend', 'resolved_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('pendingspend', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('pendingspend', 'hitl_channel',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'email+dashboard'::character varying"),
               existing_nullable=False)
    op.alter_column('dashboardnotification', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('dashboardnotification', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('dashboardnotification', 'acknowledged_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'agent_activity', type_='foreignkey')
    op.create_foreign_key(op.f('agent_activity_agent_id_fkey'), 'agent_activity', 'agent', ['agent_id'], ['agent_id'], ondelete='CASCADE')
    op.alter_column('agent_activity', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('agent', sa.Column('hitl_primary_channel', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('agent', sa.Column('hitl_phone_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('agent', sa.Column('hitl_sms_fallback_high_risk', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('agent', sa.Column('hitl_phone_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_agent_agent_id'), table_name='agent')
    op.create_index(op.f('ix_agent_agent_id'), 'agent', ['agent_id'], unique=False)
    op.create_unique_constraint(op.f('agent_agent_id_key'), 'agent', ['agent_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('agent', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('agent', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('agent', 'hmac_secret_rotated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###

